MythTV/ansible

README.md
roles/mythtv-macports/tasks/main.yml
roles/qt5/tasks/qt5-macports.yml

This update adds logic to specify mariadb-10.2 as the default database version during port install.  It also allows the user to pass in a variable specifying a different datavase version (e.g. mysql8 or mariadb-10.4) on port install.
Changes were necessary as macports was has set the default database version for support ports to different versions of mysql/mariadb.  The previous playbook would install both mysql57 and mariadb-10.2.  This update installs just one database and tells macports to install/compile the appropriate variant for all packages.
Additionally, the playbook was updated to use the p5-dbd-maridb port over p5-dbd-mysql as it is currently being better maintained.  Both are compatible with mariadb10-X and mysql57-mysql8.

update macports playbook to allow user specified database

---

roles/mythtv-macports/tasks/main.yml

Revert back to dbd-mysql since MythTV v31/master do not currently support dbd-mariadb without modifications.

macports: revert back to p5-dbd-mysql

---

roles/mythtv-macports/tasks/main.yml

macports updated libX11 to now be called xorg-libX11.  This updated fixes the playbook accordingly.

OSX: update libX11 to xorg-libX11

---

roles/mythtv-pacman/tasks/main.yml

Depending on how one installs arch, python-setuptools
may not get added to the OS.  Add it explicitly.
Fixes: #15

Archlinux: add python-setuptools to install task

---

README.md
roles/mythtv-macports/tasks/main.yml
roles/qt5/tasks/qt5-macports.yml

Updates to the OSX / macports playbook mainly due to changes over in macports.  Database default changed to mysql8 since newer versions of mariadb have scattered support.  Added new perl default version parsing since macports updated their default to 5.34 but did not link all of the "p5" packages.

OSX: Update based on recent macports update

---

roles/mythtv-macports/tasks/main.yml

Currently macports has a newer/incompatible version in its ports repo
This will need to be backed out if/when ttvdb4.py and tvmaze.py get updated
to a newer py-requests-cache

OSX: use pip3 to install py-requests

---

roles/mythtv-macports/tasks/main.yml

Add ports aom and dav1d now that they are available in the ports tree to support AV1 in FFmpeg

OSX: add ports for VA1 support in FFmpeg

---

.github/workflows/ansible.yml
.github/workflows/build-mythtv-core.yml

Fedora 37 is near EOL
Ubuntu 22.10 is no longer supported
Ubuntu 23.10 is now the current interim release

ci: update github workflow distro versions

---

roles/mythtv-deb/tasks/debian.yml
roles/mythtv-deb/tasks/ubuntu.yml
roles/mythtv-dnf/tasks/main.yml

Commit https://github.com/MythTV/mythtv/commit/8ece26b added python3-pip as build dependency (in configure) for modern Linux variants.
Updated specs for Ubuntu >= 23.04, Debian 12 and Fedora 39+.
- MythTV master for Ubuntu 23.04 is already build with python3-pip on Launchpad.
- Debian 12 has a recent version of python3-pip.
- Fedora 39, once released has python3.12 which requires python3-pip for building.
Note: For Debian and its derivatives, the package python3-pip depends on python3-wheel.
Completely untested.

Add python3-pip as build dependency

---

roles/mythtv-dnf/tasks/main.yml

Commit 273c44c5c0 introduced the typo during the
reorganization to support EL9.

Fix typo in mythtv-dnf (list -> lst) for libcrystalhd

---

README.md
hosts.yml
roles/mythtv-homebrew/tasks/main.yml
roles/mythtv-macports/tasks/main.yml

Update README.md
macport and homebrew:
- remove obsolete or repeated packages
homebrew:
- add zlib and libiconv dependencies
mysqlclient / pip
On macports, python mysqlclient needs extra help to locate mysql8+
- Add a variable to point to macports prefix directory
- Use pkg-config to locate both the MYSQLCLIENT_LDFLAGS and MYSQLCLIENT_CFLAGS variables
- Feed MYSQLCLIENT_LDFLAGS and MYSQLCLIENT_CFLAGS variables to pip to aide mysqlclient install

macOS: cleanup, mysqlclient fix, and update hombrew

---

.github/workflows/ansible.yml

This adds a "Run Workflow" button on the github actions tab for the "Run ansible-playbook" workflow.

Enable manual ansible workflow dispatch

---

.github/workflows/ansible.yml
.github/workflows/build-mythtv-core.yml
roles/mythtv-homebrew/tasks/main.yml
roles/mythtv-macports/tasks/main.yml

Cleanup depreacted ports / formula / pip installs

macOS: clean up macports and homebrew

---

roles/mythtv-macports/tasks/main.yml

Vulkan is currently broken in upstream macports.  Additionally, it is not yet in qt5/6 (a PR has been issued and in the queue).  This PR comments out the packages until both issues are resolved.

OSX: remove vulkan until its fixed upstream

---

.github/workflows/ansible.yml

For various reasons, the centos-stream-8 container points to a set of invalid mirrorlists.  Upstream has not chosen to clean this up.  While it would  be possible to adjust the workflow steps to adjust for this, just eliminate the build, as other than a few uninstalled packages (such as the kernel and grub), rocky-8 (which we also build) covers all the same packages.

Remove centos-stream-8 from ansible builds

---

roles/mythtv-dnf/tasks/main.yml

Fedora with F41 (and beyond) will not package python3-future.  Do not try to install it.

No longer attempt to install python3-future for Fedora 41 (and beyond)

---

roles/mythtv-macports/tasks/main.yml

py2app used in the macOS compile script requires setuptools to
bundles python modules into the app bundle.  Currently, py2app is
broken with setuptools versions > 70.3.0.  This should be backed out
one py2app is fixed

macOS: pin setuptools to 70.3.0

---

README.md
mythtv.yml
roles/mythtv-homebrew/tasks/main.yml
roles/mythtv-macports/tasks/main.yml
roles/pip/tasks/main.yml
roles/pip/tasks/pip-macOS.yaml

Add new pip role to consolidate python package matinenance for macOS
- Update macport and homebrew to use the new pip role
- update python modules to the latest python dependencies
Macports:
- Update python to 312. Will update to 313 when ansible to updated to allow 313 use
Homebrew:
- Correct perl module installation issue with openssl
- Update fonts packaging nameing convention
- Add mysqlclient as a required package to help with embedded python issus
Addtional work done to clean up with yamllint

macOS: Update macports, hombrew playbooks to use new pip role

---

roles/mythtv-homebrew/tasks/main.yml

Add qt-mariadb / qt-mysql now that it's an available homebrew formula.

macOS: for homebrew add qt-mariadb/qt-mysql

---

roles/mythtv-homebrew/tasks/main.yml
roles/qt6/tasks/qt6-homebrew.yml

The correct place to store the qt-mysql/qt-mariadb is in the homebrew
qt6 playbook.  Update that logic to be in line with the previously
installed database.

macOS: move qt-mysql/qt-mariadb logic in homebrew qt6 playbook

---

roles/mythtv-homebrew/tasks/main.yml
roles/mythtv-macports/tasks/main.yml
roles/python/tasks/python-macOS.yml

The ansible output occasionally confuses the "-" in package names
as a new line indicator.  Clean up the output by encapsulating the
"-" in quotes.
Additionally, attempt to correct a x86 homebrew issue where the
incorrect python is run.

macOS: clean up "-" parsing issue and update homebrew python location

---

roles/mythtv-homebrew/tasks/main.yml

- Add expat, perl-dbd-mysql, and perl DBI
- Fix issue where XviD and libX11 trip a KeyError issue due to the mismatch in capitalization in the homebrew package name (i.e. xvid and libx11)

macOS: add missing packages and fix case sensitive KeyError issue

---

roles/mythtv-macports/tasks/main.yml

Add ninja, cmake, and gpatch to macports playbook

macOS: add missing cmake essentials for macports

---

roles/python/tasks/python-macOS.yml

Correct a few mysql variables names missed in the lint cleanup

macOS: fix mysql variable names

---

roles/qt5/tasks/qt5-dnf.yml
roles/qt6/tasks/qt6-dnf.yml

Add webengine for dnf based distributions.
It is likely other distributions also need to add webengine (future work by other interested parties)

Add webengine as dependency for dnf

---

README.md
roles/qt5/tasks/qt5-macports.yml
roles/qt6/tasks/qt6-macports.yml

Remove all qtwebkit logic from macports qt5/qt6 playbooks replacing
them with qtwebengine. This isn't needed on homebrew as qtwebkit is
non-existent there as well as qtwebengine is installed by default with
qt5/qt6.
Additionally update the readme to remove the removed qtwebkit variable
hint.

macOS: Update macports to use qtwebengine

---

roles/mythtv/tasks/homebrew_macosx.yml
roles/mythtv/tasks/macports_macosx.yml

fix error where database_version is used in the status message
before being defined.

macOS: fix undefined database_version error

---

roles/mythtv/tasks/macports_macosx_post.yml

Fixed "The loop variable 'item' is already in use" warning during the macports_macosx_post.yml task

Fixed "Loop variable already in use" warning
